/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package qlttanhngu.gui;

import java.util.Date;

/**
 *
 * @author XUANVINHTD
 */
public class FrameBaoCaoDangKy extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameBaoCaoDangKy
     */
    public FrameBaoCaoDangKy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelChuCNang = new javax.swing.JPanel();
        lblThoiGianBaoCaoDK = new javax.swing.JLabel();
        dateChooserThoiGianBaoCaoDK = new com.toedter.calendar.JDateChooser();
        btnBaoCao = new javax.swing.JButton();
        btnInBaoCao = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBaoCaoDK = new javax.swing.JTable();

        setTitle("Báo Cáo Đăng Ký");
        setToolTipText("");

        panelChuCNang.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức Năng"));

        lblThoiGianBaoCaoDK.setText("Thời Gian Lập Báo Cáo");

        dateChooserThoiGianBaoCaoDK.setDateFormatString("dd/MM/YYYY");
        dateChooserThoiGianBaoCaoDK.setEnabled(false);
        dateChooserThoiGianBaoCaoDK.setDate(new Date());

        btnBaoCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/inBill.png"))); // NOI18N
        btnBaoCao.setText("Báo Cáo");

        btnInBaoCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Printer-icon.png"))); // NOI18N
        btnInBaoCao.setText("In Báo Cáo");

        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Close1.png"))); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelChuCNangLayout = new javax.swing.GroupLayout(panelChuCNang);
        panelChuCNang.setLayout(panelChuCNangLayout);
        panelChuCNangLayout.setHorizontalGroup(
            panelChuCNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChuCNangLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblThoiGianBaoCaoDK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateChooserThoiGianBaoCaoDK, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(btnBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnInBaoCao)
                .addGap(68, 68, 68)
                .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        panelChuCNangLayout.setVerticalGroup(
            panelChuCNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChuCNangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelChuCNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelChuCNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBaoCao)
                        .addComponent(btnInBaoCao)
                        .addComponent(btnDong))
                    .addGroup(panelChuCNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblThoiGianBaoCaoDK)
                        .addComponent(dateChooserThoiGianBaoCaoDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tableBaoCaoDK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableBaoCaoDK);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(panelChuCNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelChuCNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaoCao;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnInBaoCao;
    private com.toedter.calendar.JDateChooser dateChooserThoiGianBaoCaoDK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblThoiGianBaoCaoDK;
    private javax.swing.JPanel panelChuCNang;
    private javax.swing.JTable tableBaoCaoDK;
    // End of variables declaration//GEN-END:variables
}
