/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package qlttanhngu.gui;

import Assest.StoreSave;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import qlttanhngu.bo.CTHocVienBO;
import qlttanhngu.controller.CTHocVienController;
import qlttanhngu.controller.HocVienController;
import qlttanhngu.controller.LopHocController;
import qlttanhngu.dto.CTHocVienDTO;
import qlttanhngu.dto.DanhSachThiDTO;
import qlttanhngu.dto.LopHocDTO;

/**
 *
 * @author XUANVINHTD
 */
public class FrameXepLop extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameXepLop
     */
    public FrameXepLop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelXepLop = new javax.swing.JPanel();
        lblMaLop = new javax.swing.JLabel();
        lblTenLop = new javax.swing.JLabel();
        lblGiangVien = new javax.swing.JLabel();
        lblChuongTrinhHoc = new javax.swing.JLabel();
        txtGiangVien = new javax.swing.JTextField();
        txtChuongTrinhHoc = new javax.swing.JTextField();
        lblKhoaHoc = new javax.swing.JLabel();
        lblDiemDauVao = new javax.swing.JLabel();
        lblPhong = new javax.swing.JLabel();
        txtKhoaHoc = new javax.swing.JTextField();
        txtDiemDauVao = new javax.swing.JTextField();
        txtPhong = new javax.swing.JTextField();
        panelChucNang = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnChTiet = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        comboBoxMaLop = new javax.swing.JComboBox();
        txtTenLop = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        lblSoLuong = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDSHocVien = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDSHocVienCuaLop = new javax.swing.JTable();
        btnChonTatCa = new javax.swing.JButton();
        btnChonDon = new javax.swing.JButton();
        btnXoaTatCa = new javax.swing.JButton();
        btnXoaDon = new javax.swing.JButton();

        setTitle("Xếp Lớp");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelXepLop.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin"));

        lblMaLop.setText("Mã Lớp");

        lblTenLop.setText("Tên Lớp");

        lblGiangVien.setText("Giảng Viên");

        lblChuongTrinhHoc.setText("Tên Chương Trình Học");

        txtGiangVien.setEnabled(false);

        txtChuongTrinhHoc.setEnabled(false);

        lblKhoaHoc.setText("Tên Khóa Học");

        lblDiemDauVao.setText("Điểm Thi Đầu Vào Yêu Cầu");

        lblPhong.setText("Phòng");

        txtKhoaHoc.setEnabled(false);

        txtDiemDauVao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiemDauVaoKeyTyped(evt);
            }
        });

        txtPhong.setEnabled(false);

        panelChucNang.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức Năng"));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Buttonadd.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnChTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ChiTiet.png"))); // NOI18N
        btnChTiet.setText("Chi Tiết ");
        btnChTiet.setToolTipText("Cho Biết Danh Sách Các Học Viên Trong Từng Lớp");
        btnChTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChTietActionPerformed(evt);
            }
        });

        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Close1.png"))); // NOI18N
        btnDong.setText("Dóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelChucNangLayout = new javax.swing.GroupLayout(panelChucNang);
        panelChucNang.setLayout(panelChucNangLayout);
        panelChucNangLayout.setHorizontalGroup(
            panelChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChucNangLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnChTiet)
                .addGap(31, 31, 31)
                .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        panelChucNangLayout.setVerticalGroup(
            panelChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChucNangLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnDong)
                    .addComponent(btnLuu)
                    .addComponent(btnChTiet))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        comboBoxMaLop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxMaLopItemStateChanged(evt);
            }
        });

        txtTenLop.setEnabled(false);

        txtSoLuong.setEnabled(false);
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });
        txtSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyTyped(evt);
            }
        });

        lblSoLuong.setText("Số lượng");

        javax.swing.GroupLayout panelXepLopLayout = new javax.swing.GroupLayout(panelXepLop);
        panelXepLop.setLayout(panelXepLopLayout);
        panelXepLopLayout.setHorizontalGroup(
            panelXepLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelXepLopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelXepLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTenLop)
                    .addComponent(lblMaLop)
                    .addComponent(lblDiemDauVao)
                    .addComponent(lblSoLuong))
                .addGap(30, 30, 30)
                .addGroup(panelXepLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemDauVao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelXepLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKhoaHoc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhong, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGiangVien, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblChuongTrinhHoc, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(panelXepLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGiangVien, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(txtKhoaHoc)
                    .addComponent(txtPhong)
                    .addComponent(txtChuongTrinhHoc))
                .addGap(18, 18, 18)
                .addComponent(panelChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelXepLopLayout.setVerticalGroup(
            panelXepLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXepLopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelXepLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelXepLopLayout.createSequentialGroup()
                        .addGroup(panelXepLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaLop)
                            .addComponent(lblKhoaHoc)
                            .addComponent(txtKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelXepLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenLop)
                            .addComponent(txtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhong)
                            .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelXepLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGiangVien)
                            .addComponent(txtGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiemDauVao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiemDauVao))
                        .addGap(25, 25, 25)
                        .addGroup(panelXepLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChuongTrinhHoc)
                            .addComponent(txtChuongTrinhHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoLuong)))
                    .addComponent(panelChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        tableDSHocVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDSHocVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDSHocVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDSHocVien);

        tableDSHocVienCuaLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDSHocVienCuaLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDSHocVienCuaLopMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableDSHocVienCuaLop);

        btnChonTatCa.setText(">>");
        btnChonTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonTatCaActionPerformed(evt);
            }
        });

        btnChonDon.setText(">");
        btnChonDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonDonActionPerformed(evt);
            }
        });

        btnXoaTatCa.setText("<<");
        btnXoaTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTatCaActionPerformed(evt);
            }
        });

        btnXoaDon.setText("<");
        btnXoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChonTatCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChonDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaTatCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelXepLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelXepLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChonTatCa)
                        .addGap(18, 18, 18)
                        .addComponent(btnChonDon)
                        .addGap(27, 27, 27)
                        .addComponent(btnXoaTatCa)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaDon)
                        .addGap(0, 296, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChTietActionPerformed
         if(frameChiTietXepLop == null || frameChiTietXepLop.isClosed())
         {
           InitFrameInternal(new FrameChiTietXepLop());
         } 
    }//GEN-LAST:event_btnChTietActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        try {
                 hashMapTenLop = new LopHocController().GetListLopHoc();
                 DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel(hashMapTenLop.keySet().toArray());
                //set model cho comboBoxMaLop
                 comboBoxMaLop.setModel(defaultComboBoxModel);
                 
                 
        } catch (Exception ex) {
            Logger.getLogger(FrameXepLop.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formInternalFrameActivated

    private void comboBoxMaLopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxMaLopItemStateChanged
        
        try {
            List<LopHocDTO> listlh = new ArrayList<LopHocDTO>();
            listlh = new LopHocController().LoadListLopHocTheoMaLop(this.comboBoxMaLop.getSelectedItem().toString());
            txtTenLop.setText(new LopHocController().GetListLopHoc().get(listlh.get(0).getMaLop()));
//            comboBoxTenLop.setSelectedItem(new LopHocController().GetListLopHoc().get(listlh.get(0).getMaLop()));
            txtChuongTrinhHoc.setText(new LopHocController().GetListChuongTrinhHoc().get(listlh.get(0).getMaChuongTrinhHoc()));
            txtGiangVien.setText(new LopHocController().GetListGiangVien().get(listlh.get(0).getMaNhanVien()));
            txtPhong.setText(new LopHocController().GetListPhongHoc().get(listlh.get(0).getMaPhong()));
            txtKhoaHoc.setText(new LopHocController().GetListKhoaHoc().get(listlh.get(0).getMaKhoaHoc()));
            txtSoLuong.setText(new LopHocController().GetListSoLuongHocVienTrongPhong().get(txtPhong.getText()).toString());
            
            //tableDSHocVienCuaLop.setModel(new CTHocVienController().LoadListHocVienTheoLop(this.comboBoxMaLop.getSelectedItem().toString()));
            this.TenLopChange();
        } catch (Exception ex) {
            Logger.getLogger(FrameXepLop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboBoxMaLopItemStateChanged

    private void btnChonTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonTatCaActionPerformed
        // lấy tất cả học viên qua danh sách phòng
        int soluong = Integer.parseInt(txtSoLuong.getText());
        //không có dữ liệu thì ko dc add
        if (tableDSHocVien.getRowCount() == 0 || soluong == tableDSHocVienCuaLop.getRowCount()) {
            return;
        }
        for (int i = 0; i < soluong; i++) {
            if (tableDSHocVien.getRowCount() == 0) {
                return;
            }
            maHocVien = tableDSHocVien.getValueAt(0, 0).toString();
            tenHocVien = tableDSHocVien.getValueAt(0, 1).toString();
            ketQuaThi = Double.parseDouble(tableDSHocVien.getValueAt(0,2).toString());
            rowIndexDSHV = 0;
            this.btnChonDonActionPerformed(evt);
        }
    }//GEN-LAST:event_btnChonTatCaActionPerformed

    private void btnChonDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonDonActionPerformed
        DefaultTableModel defaultTableModel = (DefaultTableModel) tableDSHocVienCuaLop.getModel();

        //kiểm tra số lượng trong phòng
        int soluong = Integer.parseInt(txtSoLuong.getText());
        if(soluong == tableDSHocVienCuaLop.getRowCount()){
            JOptionPane.showMessageDialog(this, "Phòng đã đầy! !");
            return;
        }
        //kiểm tra xem đã chọn dòng chưa.
        if (maHocVien == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn học viên trước khi thêm !");
            return;
        }
        //kiểm tra xem học viên  đã được add chưa
        if (tableDSHocVienCuaLop.getRowCount() != 0) {
            
            for (int i = 0; i < tableDSHocVienCuaLop.getRowCount(); i++) {
                if (tableDSHocVienCuaLop.getValueAt(i, 0).toString().equals(maHocVien)) {
                    JOptionPane.showMessageDialog(this, "Học vên này đã tồn tại !");
                    return;
                }
            }
        }
        
        //add thêm học viên vào table phòng thi
        Vector row = new Vector();
        row.add(maHocVien);
        row.add(tenHocVien);
        row.add(ketQuaThi);
        defaultTableModel.addRow(row);
        //xóa dòng bên danh sách học viên
        if (tableDSHocVien.getRowCount() >= rowIndexDSHV) {
            ((DefaultTableModel) tableDSHocVien.getModel()).removeRow(rowIndexDSHV);
        }
        maHocVien = null;
        tenHocVien = null;
        ketQuaThi = null;
    }//GEN-LAST:event_btnChonDonActionPerformed

    private void btnXoaTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTatCaActionPerformed
        // lấy tất cả học viên qua danh sách phòng
        int soluong = Integer.parseInt(txtSoLuong.getText());
        int soluongphong = tableDSHocVienCuaLop.getRowCount();
        //không có dữ liệu thì ko dc add
        if (tableDSHocVienCuaLop.getRowCount() == 0) {
            return;
        }
        for (int i = 0; i < (soluong); i++) {
            if (tableDSHocVienCuaLop.getRowCount() == 0) {
                return;
            }
            maHocVien = tableDSHocVienCuaLop.getValueAt(0, 0).toString();
            tenHocVien = tableDSHocVienCuaLop.getValueAt(0, 1).toString();
            ketQuaThi = Double.parseDouble(tableDSHocVienCuaLop.getValueAt(0,2).toString());
            rowIndexDSHV = 0;
            this.btnXoaDonActionPerformed(evt);
        }
    }//GEN-LAST:event_btnXoaTatCaActionPerformed
    
    private void btnXoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDonActionPerformed
        DefaultTableModel defaultTableModel = (DefaultTableModel) tableDSHocVien.getModel();

        //kiểm tra xem đã chọn dòng chưa.
        if (maHocVien == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn học viên trước khi xóa !");
            return;
        }
        //kiểm tra xem học viên  đã được add chưa
        if (tableDSHocVien.getRowCount() != 0) {
            for (int i = 0; i < tableDSHocVien.getRowCount(); i++) {
                if (tableDSHocVien.getValueAt(i, 0).toString().equals(maHocVien)) {
                    JOptionPane.showMessageDialog(this, "Học vên này đã tồn tại !");
                    return;
                }
            }
        }

        //add thêm học viên vào table phòng thi
        Vector row = new Vector();
        row.add(maHocVien);
        row.add(tenHocVien);
        row.add(ketQuaThi);
        defaultTableModel.addRow(row);
        //xóa dòng bên danh sách học viên
        if (tableDSHocVienCuaLop.getRowCount() >= rowIndexDSHV) {
            ((DefaultTableModel) tableDSHocVienCuaLop.getModel()).removeRow(rowIndexDSHV);
        }
        maHocVien = null;
        tenHocVien = null;
        ketQuaThi = null;
    }//GEN-LAST:event_btnXoaDonActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if("".equals(txtTenLop.getText()))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn lớp trước khi thêm! ");
            return;
        }
        if("".equals(txtDiemDauVao.getText()))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Điểm đầu vào trước khi thêm! ");
            return;
        }
        if("".equals(txtSoLuong.getText()))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Số lượng trước khi thêm! ");
            return;
        }
        try {
            tableDSHocVien.setModel(new HocVienController().GetListListHocVienTheoDiemYeuCau(Double.parseDouble(txtDiemDauVao.getText())));
        } catch (Exception ex) {
            Logger.getLogger(FrameXepLop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void tableDSHocVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDSHocVienMouseClicked
        JTable jTable1 = (JTable) evt.getSource();

        rowIndexDSHV = jTable1.getSelectedRow();

        //lưu lại các giá trị để dùng add qua bảng khác
        if (jTable1.getValueAt(0, 0) == null) {
            return;
        }
        maHocVien = jTable1.getValueAt(rowIndexDSHV, 0).toString();
        tenHocVien = jTable1.getValueAt(rowIndexDSHV, 1).toString();
        ketQuaThi = Double.parseDouble(jTable1.getValueAt(rowIndexDSHV, 2).toString());
    }//GEN-LAST:event_tableDSHocVienMouseClicked

    private void tableDSHocVienCuaLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDSHocVienCuaLopMouseClicked
        tableHVDaCHon = (JTable) evt.getSource();

        rowIndexDSHV = tableHVDaCHon.getSelectedRow();

        //lưu lại các giá trị để dùng add qua bảng khác
        if (tableHVDaCHon.getValueAt(0, 0) == null) {
            return;
        }
        maHocVien = tableHVDaCHon.getValueAt(rowIndexDSHV, 0).toString();
        tenHocVien = tableHVDaCHon.getValueAt(rowIndexDSHV, 1).toString();
        ketQuaThi = Double.parseDouble(tableHVDaCHon.getValueAt(rowIndexDSHV, 2).toString());
    }//GEN-LAST:event_tableDSHocVienCuaLopMouseClicked

    private void txtDiemDauVaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiemDauVaoKeyTyped
       char vChar = evt.getKeyChar();
        int len = txtDiemDauVao.getText().length();

        if (!(Character.isDigit(vChar))
            || (vChar == KeyEvent.VK_BACK_SPACE)
            || (vChar == KeyEvent.VK_DELETE)
            || (vChar == KeyEvent.VK_ENTER)
            || (vChar == KeyEvent.VK_TAB) || (len > 2)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDiemDauVaoKeyTyped

    private void txtSoLuongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongKeyTyped
        char vChar = evt.getKeyChar();
        int len = txtSoLuong.getText().length();

        if (!(Character.isDigit(vChar))
            || (vChar == KeyEvent.VK_BACK_SPACE)
            || (vChar == KeyEvent.VK_DELETE)
            || (vChar == KeyEvent.VK_ENTER)
            || (vChar == KeyEvent.VK_TAB) || (len > 1)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSoLuongKeyTyped

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        try {
            
            Boolean result = false; 
            if (tableDSHocVienCuaLop.getRowCount() == 0 && tableDSHocVienCuCuaLop.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng xếp phòng cho học viên trước khi lưu !");
                return;
            }
            int row1 = tableDSHocVienCuaLop.getRowCount();
            int row2 = tableDSHocVienCuCuaLop.getRowCount();
            
            Vector<String> lstStr = new Vector<>();
            
            for (int k = 0; k < row2; k++) {
                lstStr.add(tableDSHocVienCuCuaLop.getValueAt(k, 0).toString());
            }
            
            for (int i = 0; i < row1; i++) {
                if (!lstStr.contains(tableDSHocVienCuaLop.getValueAt(i, 0))) {
                    try {
                        CTHocVienDTO cthocviendto = new CTHocVienDTO();
                        cthocviendto.setMaLop(comboBoxMaLop.getSelectedItem().toString());
                        cthocviendto.setMaHocVien(tableDSHocVienCuaLop.getValueAt(i, 0).toString());
                        
                        result = new CTHocVienBO().ThemCTHocVien(cthocviendto);
                    } catch (Exception ex) {
                        Logger.getLogger(FrameXepLop.class.getName()).log(Level.SEVERE, null, ex);
                        return;
                    }
                }
            }
            if (result) {
                JOptionPane.showMessageDialog(this, "Lưu thành công !");
            }
        
        
        //Xóa
        
        Vector<String> lstStr1 = new Vector<>();
            for (int k = 0; k < row1; k++) {
                lstStr1.add(tableDSHocVienCuaLop.getValueAt(k, 0).toString());
            }
            if (row1 < row2) {
                for (int j = 0; j < row2; j++) {
                    if (!lstStr1.contains(tableDSHocVienCuCuaLop.getValueAt(j, 0))) {
                        try {
                                CTHocVienDTO cthocviendto = new CTHocVienDTO();
                                cthocviendto.setMaLop(this.comboBoxMaLop.getSelectedItem().toString());
                                cthocviendto.setMaHocVien(tableDSHocVienCuCuaLop.getValueAt(j, 0).toString());
//                            
                            result = new CTHocVienBO().DeleteCTHocVien(cthocviendto);
                        } catch (Exception ex) {
                            Logger.getLogger(FrameQuanTri.class.getName()).log(Level.SEVERE, null, ex);
                            return;
                        }
                    }
                }
            }
            if (result) {
                JOptionPane.showMessageDialog(this, "Lưu thành công !");
            }
//            //câp nhật giá trị lại bản cũ
            TenLopChange();
        } catch (Exception ex) {
            Logger.getLogger(FrameXepLop.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnLuuActionPerformed

     //Khởi Tạo các frameInternal
    private void InitFrameInternal(JInternalFrame jInternalFrame)
    {         
           StoreSave.desktop.add(jInternalFrame);

              try {
                     jInternalFrame.setMaximum(true);
                 } catch (PropertyVetoException ex) {
                     Logger.getLogger(FrameMain.class.getName()).log(Level.SEVERE, null, ex);
                 }
               jInternalFrame.show();
    }
    
    
    private String getKey(HashMap hashMap, String value) {
        for (Object s : hashMap.keySet()) {
            if (hashMap.get(s).equals(value)) {
                return (String) s;
            }
        }
        return null;
    }
    
    private void TenLopChange(){
        try {
            tableDSHocVienCuCuaLop.setModel(new CTHocVienController().LoadListHocVienTheoLop(this.comboBoxMaLop.getSelectedItem().toString()));
            tableDSHocVienCuaLop.setModel(new CTHocVienController().LoadListHocVienTheoLop(this.comboBoxMaLop.getSelectedItem().toString()));
        } catch (Exception ex) {
            Logger.getLogger(FrameXepLop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private JTable tableDSHocVienCuCuaLop = new JTable();
    public JTable GetTableDSHVDaChon(){
        return tableDSHocVienCuaLop;
    }
    public javax.swing.JComboBox GetcomboBoxMaLop(){
        return comboBoxMaLop;
    }
    
    public javax.swing.JTextField GettxtTenLop(){
        return txtTenLop;
    }
    public JTable tableHVDaCHon;
    private int rowIndexDSHV;
    private String maHocVien;
    private String tenHocVien;
    private Double ketQuaThi;
    private HashMap hashMapTenLop;
    private FrameChiTietXepLop frameChiTietXepLop;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChTiet;
    private javax.swing.JButton btnChonDon;
    private javax.swing.JButton btnChonTatCa;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoaDon;
    private javax.swing.JButton btnXoaTatCa;
    private javax.swing.JComboBox comboBoxMaLop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblChuongTrinhHoc;
    private javax.swing.JLabel lblDiemDauVao;
    private javax.swing.JLabel lblGiangVien;
    private javax.swing.JLabel lblKhoaHoc;
    private javax.swing.JLabel lblMaLop;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenLop;
    private javax.swing.JPanel panelChucNang;
    private javax.swing.JPanel panelXepLop;
    private javax.swing.JTable tableDSHocVien;
    private javax.swing.JTable tableDSHocVienCuaLop;
    private javax.swing.JTextField txtChuongTrinhHoc;
    private javax.swing.JTextField txtDiemDauVao;
    private javax.swing.JTextField txtGiangVien;
    private javax.swing.JTextField txtKhoaHoc;
    private javax.swing.JTextField txtPhong;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenLop;
    // End of variables declaration//GEN-END:variables
}
