/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package qlttanhngu.gui;

import Assest.StoreSave;
import com.sun.org.apache.xml.internal.utils.StopParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.text.MaskFormatter;
import qlttanhngu.controller.HocVienController;
import qlttanhngu.dto.HocVienDTO;

/**
 *
 * @author XUANVINHTD
 */
public class FrameCapNhatHocVien extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameCapNhatHocVien
     */
    public FrameCapNhatHocVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTTCaNhan = new javax.swing.JPanel();
        lblHoTen = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        lblCMND = new javax.swing.JLabel();
        lblSoDT = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        txtSoDT = new javax.swing.JTextField();
        dateChooserNgaySinh = new com.toedter.calendar.JDateChooser();
        comboxTinhTrangHoc = new javax.swing.JComboBox();
        txtEmail = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        panelChuCNang = new javax.swing.JPanel();
        btnLuu = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        comboxGioiTinh = new javax.swing.JComboBox();
        lblMaHocVien = new javax.swing.JLabel();
        txtMaHocVien = new javax.swing.JTextField();
        lblMaChungChi = new javax.swing.JLabel();
        lblNgheNghiep = new javax.swing.JLabel();
        txtNgheNghiep = new javax.swing.JTextField();
        lblSoLuongCuocHen = new javax.swing.JLabel();
        txtSoLuongCuocHen = new javax.swing.JTextField();
        comboBoxTenChungChi = new javax.swing.JComboBox();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelTTCaNhan.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Cá Nhân"));

        lblHoTen.setText("Họ Tên");

        lblNgaySinh.setText("Ngày Sinh");

        lblCMND.setText("CMND");

        lblSoDT.setText("Số Điện thoại");

        lblEmail.setText("Email");

        lblDiaChi.setText("Địa Chỉ");

        jLabel7.setText("Giới Tính");

        jLabel8.setText("Tình Trạng Học");

        txtHoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoTenKeyPressed(evt);
            }
        });

        txtCMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCMNDKeyPressed(evt);
            }
        });

        txtSoDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoDTKeyPressed(evt);
            }
        });

        dateChooserNgaySinh.setDateFormatString("dd/MM/yyyy");

        comboxTinhTrangHoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tiềm Năng", "Chính Thức" }));

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        txtDiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiaChiKeyPressed(evt);
            }
        });

        panelChuCNang.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức Năng"));

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Close1.png"))); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelChuCNangLayout = new javax.swing.GroupLayout(panelChuCNang);
        panelChuCNang.setLayout(panelChuCNangLayout);
        panelChuCNangLayout.setHorizontalGroup(
            panelChuCNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChuCNangLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelChuCNangLayout.setVerticalGroup(
            panelChuCNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChuCNangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChuCNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnDong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        comboxGioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));

        lblMaHocVien.setText("Mã Học VIên");

        txtMaHocVien.setEnabled(false);

        lblMaChungChi.setText("Tên Chứng Chỉ");

        lblNgheNghiep.setText("Nghề nghiệp");

        txtNgheNghiep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNgheNghiepKeyPressed(evt);
            }
        });

        lblSoLuongCuocHen.setText("Số lượng cuộc hẹn");

        txtSoLuongCuocHen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoLuongCuocHenKeyPressed(evt);
            }
        });

        try{
            comboBoxTenChungChi.setModel(new HocVienController().GetListTenChungChi());
        }catch(Exception e){

        }

        javax.swing.GroupLayout panelTTCaNhanLayout = new javax.swing.GroupLayout(panelTTCaNhan);
        panelTTCaNhan.setLayout(panelTTCaNhanLayout);
        panelTTCaNhanLayout.setHorizontalGroup(
            panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTTCaNhanLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSoDT)
                        .addComponent(lblCMND, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lblNgaySinh)
                    .addComponent(lblHoTen)
                    .addComponent(lblMaHocVien)
                    .addComponent(lblMaChungChi))
                .addGap(18, 18, 18)
                .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaHocVien, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboBoxTenChungChi, javax.swing.GroupLayout.Alignment.LEADING, 0, 197, Short.MAX_VALUE)
                        .addComponent(txtSoDT, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCMND, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(lblDiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblNgheNghiep, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lblSoLuongCuocHen))
                .addGap(30, 30, 30)
                .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTTCaNhanLayout.createSequentialGroup()
                        .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelTTCaNhanLayout.createSequentialGroup()
                        .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSoLuongCuocHen, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboxTinhTrangHoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addComponent(panelChuCNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        panelTTCaNhanLayout.setVerticalGroup(
            panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTTCaNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHocVien)
                    .addComponent(txtMaHocVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgheNghiep)
                    .addComponent(txtNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTTCaNhanLayout.createSequentialGroup()
                        .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoTen)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNgaySinh)
                            .addComponent(dateChooserNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCMND)
                            .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSoDT)
                            .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTTCaNhanLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSoLuongCuocHen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSoLuongCuocHen)))
                            .addGroup(panelTTCaNhanLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboBoxTenChungChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMaChungChi)))))
                    .addGroup(panelTTCaNhanLayout.createSequentialGroup()
                        .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(comboxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiaChi)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(comboxTinhTrangHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(panelChuCNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTTCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTTCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        HocVienDTO hocviendto = new HocVienDTO();
        //Kiểm tra mã, họ tên không dc null, kiểm tra kiễu dữ số dt, ......
        if ("".equals(txtMaHocVien.getText()) || "".equals(txtHoTen.getText()) || Kitu(txtCMND.getText()) || Kitu(txtSoDT.getText()) || Kitu(txtSoLuongCuocHen.getText())){
            MessageBoxError messageBoxErorHocVien = new MessageBoxError();
            StoreSave.desktop.add(messageBoxErorHocVien);
            messageBoxErorHocVien.setBounds(400, 300, 380, 120);
            messageBoxErorHocVien.show();
            return;
        }
        try {

            hocviendto.setMaHocVien(txtMaHocVien.getText());
            hocviendto.setCmnd(txtCMND.getText());
            hocviendto.setDiaChi(txtDiaChi.getText());
            hocviendto.setEmail(txtEmail.getText());
            hocviendto.setGioiTinh(comboxGioiTinh.getSelectedItem() == "Nam" ? true : false);
            hocviendto.setTenMaChungChi(comboBoxTenChungChi.getSelectedItem().toString());
            hocviendto.setNamSinh(dateChooserNgaySinh.getDate());
            hocviendto.setNgheNghiep(txtNgheNghiep.getText());
            hocviendto.setSoDienThoai(Integer.parseInt("".equals(txtSoDT.getText()) ? "0" : txtSoDT.getText()));
            hocviendto.setSoLuongLienLac(Integer.parseInt("".equals(txtSoLuongCuocHen.getText()) ? "0" : txtSoLuongCuocHen.getText()));
            hocviendto.setTenHocVien(txtHoTen.getText());
            hocviendto.setTinhTrangHoc(comboxTinhTrangHoc.getSelectedIndex() == 1 ? false : true);

            //Kiểm tra xem có chắc chắn cập nhât không? 
            MessageBoxHocVien messageBoxHocVien = new MessageBoxHocVien();
            StoreSave.desktop.add(messageBoxHocVien);
            messageBoxHocVien.setBounds(400, 250, 511, 189);
            messageBoxHocVien.show();

            //Lay thong tin de cap nhat
            StoreSave.hocvien = hocviendto;

        } catch (Exception ex) {
            Logger.getLogger(FrameDSHocVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        //load lại frame danh sach hoc viên
        // StoreSave.frameDSHocVien.refreshTable();      
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    //Load dữ liệu vào các compoment của frame
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        if (StoreSave.hocvien != null) {
            txtMaHocVien.setText(StoreSave.hocvien.getMaHocVien());
            txtHoTen.setText(StoreSave.hocvien.getTenHocVien());
            txtCMND.setText(StoreSave.hocvien.getCmnd());
            dateChooserNgaySinh.setDate(StoreSave.hocvien.getNamSinhUpdate());
            comboxGioiTinh.setSelectedIndex(StoreSave.hocvien.getGioiTinh() == "Nam" ? 0 : 1);
            comboBoxTenChungChi.setSelectedItem(StoreSave.hocvien.getTenChungChi());
            txtNgheNghiep.setText(StoreSave.hocvien.getNgheNghiep());
            txtSoDT.setText(StoreSave.hocvien.getSoDienThoai().toString());
            txtDiaChi.setText(StoreSave.hocvien.getDiaChi());
            txtEmail.setText(StoreSave.hocvien.getEmail());
            txtSoLuongCuocHen.setText(StoreSave.hocvien.getSoLuongLienLac().toString());
            comboxTinhTrangHoc.setSelectedIndex(StoreSave.hocvien.getTinhTrangHoc() == "Chính Thức" ? 0 : 1);
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void txtHoTenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoTenKeyPressed
        if (txtHoTen.getText().length() > 50) {
            txtHoTen.setText(txtHoTen.getText().substring(0, 50));
        }
    }//GEN-LAST:event_txtHoTenKeyPressed

    private void txtCMNDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCMNDKeyPressed
  
        if (txtCMND.getText().length() > 11) {
            txtCMND.setText(txtCMND.getText().substring(0, 11));
        }
    }//GEN-LAST:event_txtCMNDKeyPressed

    private void txtSoDTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoDTKeyPressed
        if (txtSoDT.getText().length() > 11) {
            txtSoDT.setText(txtSoDT.getText().substring(0, 11));
        }
    }//GEN-LAST:event_txtSoDTKeyPressed

    private void txtNgheNghiepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNgheNghiepKeyPressed
        if (txtNgheNghiep.getText().length() > 120) {
            txtNgheNghiep.setText(txtNgheNghiep.getText().substring(0, 120));
        }
    }//GEN-LAST:event_txtNgheNghiepKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if (txtEmail.getText().length() > 20) {
            txtEmail.setText(txtEmail.getText().substring(0, 20));
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtDiaChiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaChiKeyPressed
        if (txtDiaChi.getText().length() > 100) {
            txtDiaChi.setText(txtDiaChi.getText().substring(0, 100));
        }
    }//GEN-LAST:event_txtDiaChiKeyPressed

    private void txtSoLuongCuocHenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongCuocHenKeyPressed
         if (txtSoLuongCuocHen.getText().length() > 2) {
            txtSoLuongCuocHen.setText(txtSoLuongCuocHen.getText().substring(0, 2));
        }
    }//GEN-LAST:event_txtSoLuongCuocHenKeyPressed

    /// Loi So ///
    public boolean LoiSo(String str) {
        Pattern pt = Pattern.compile("[0-9]");
        Matcher mc = pt.matcher(str);
        if (!mc.find()) {
            return false;
        }
        return true;
    }

    public boolean Kitu(String str5) {
        Pattern pt = Pattern.compile("[a-zA-Z]");
        Matcher mc = pt.matcher(str5);
        if (!mc.find()) {
            return false;
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnLuu;
    private javax.swing.JComboBox comboBoxTenChungChi;
    private javax.swing.JComboBox comboxGioiTinh;
    private javax.swing.JComboBox comboxTinhTrangHoc;
    private com.toedter.calendar.JDateChooser dateChooserNgaySinh;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCMND;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMaChungChi;
    private javax.swing.JLabel lblMaHocVien;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNgheNghiep;
    private javax.swing.JLabel lblSoDT;
    private javax.swing.JLabel lblSoLuongCuocHen;
    private javax.swing.JPanel panelChuCNang;
    private javax.swing.JPanel panelTTCaNhan;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaHocVien;
    private javax.swing.JTextField txtNgheNghiep;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtSoLuongCuocHen;
    // End of variables declaration//GEN-END:variables
}
